### ISSUE TITLE
 getPluginCreator could not find plugin VoxelGeneratorV1 version 001

### ISSUE THREAD

**Issue by LeftThink** [Qiuzhongyuan/pointpillars_pytorch_trt#10]
I export onnx success,but when execute unit_test report this error:
INVALID_ARGUMENT: getPluginCreator could not find plugin VoxelGeneratorV1 version 001

**Comment by LeftThink** [comment]
> I export onnx success,but when execute unit_test report this error:
> INVALID_ARGUMENT: getPluginCreator could not find plugin VoxelGeneratorV1 version 001

I solved it

**Comment by windzu** [comment]
> > I export onnx success,but when execute unit_test report this error:
> > INVALID_ARGUMENT: getPluginCreator could not find plugin VoxelGeneratorV1 version 001
> 
> I solved it

I encountered the same problem. How did you solve it?

**Comment by sean-wade** [comment]
I encountered the same problem. How did you solve it?

Thanks for reply us~
