### ISSUE TITLE
no MAP_TO_BEV in pruning model

### ISSUE THREAD

**Issue by chasingw** [Qiuzhongyuan/pointpillars_pytorch_trt#6]
where is MAP_TO_BEV module in model？
https://github.com/Qiuzhongyuan/pointpillars_pytorch_trt/blob/7b6063bbd02159741b204946ed8249117f836498/pytorch/tools/pruning.py#L147-L160

**Comment by Qiuzhongyuan** [comment]
please ignore the pruning.py，because we do not release the pruning tools.

**Comment by chasingw** [comment]
> please ignore the pruning.py，because we do not release the pruning tools.

Alright, thanks for your reply.
