### ISSUE TITLE
pointpillars_large_model.onnx model shape means（ inputs & outputs ）

### ISSUE THREAD

**Issue by Ryze0124** [Qiuzhongyuan/pointpillars_pytorch_trt#7]
pointpillars_large_model.onnx model has two outputs (pointpillars_output1 & pointpillars_output2), can you help me to explain their shape mesns（outputs all is 1 x 100 x 9）， and VoxelGeneratorV1  is dynamic plugin，but onnx model input is fixed （25000 x 5），why？

**Comment by Qiuzhongyuan** [comment]
1. 'nms_post_maxsize' in NMS layer is 100, so the outputs' dim 1 is 100, 9 means xyzlwhr+score + cls_idx for per box; 
2. pcs are different between frames, so we must set a big shape for all the frames. in kitti reduced pcs, 25000 is enough,the 'valid' tensor will be used to filter the data.
3. all the fixed shape is used to deploy model with tensorrt more easily
